serverFiles:
  alerting_rules.yml:
    groups:
      - name: Instances
        rules:
          - alert: PodFailed
            expr:
              kube_pod_status_phase{phase="Failed"} > 0
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Pod has failed "
              description: "A pod has failed."

