apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pj-production-deployment
  namespace: production
  labels:
    app: go-pj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-pj
  template:
    metadata:
      labels:
        app: go-pj
    spec:
      containers:
        - name: go-pj-container
          image: go-pj:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080