apiVersion: v1
kind: Service
metadata:
  name: go-pj-development-deployment
  namespace: development
spec:
  selector:
    app: custom-go-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080
  type: NodePort  # so each node redirects 31080 to 8080
