apiVersion: v1
kind: Service
metadata:
  name: go-pj-production-service
  namespace: production
spec:
  selector:
    app: go-pj
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31081
  type: NodePort  # so each node redirects 31081 to 8081