apiVersion: v1
kind: Service
metadata:
  name: go-pj-development-deployment
  namespace: development
spec:
  selector:
    app: custom-go-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31081
  type: NodePort  # so each node redirects 31080 to 8080
